import { useEffect, useMemo, useState } from "react";
import "./AutoApply.css";
type Job = { title:string; company:string; location?:string; url:string; source?:string; score?:number };
type Application = { id?:number; url:string; company?:string; title?:string; adapter?:string; status:string; reason?:string };
const API=import.meta.env.VITE_AUTO_APPLY_API||"http://127.0.0.1:8000";
const FRESHERSHUNT="https://freshershunt.in/off-campus-drive-jobs/";
export default function AutoApply(){
 const [jobs,setJobs]=useState<Job[]>([]),[applications,setApplications]=useState<Application[]>([]),[urls,setUrls]=useState(""),[minimumScore,setMinimumScore]=useState(50),[dryRun,setDryRun]=useState(true),[loading,setLoading]=useState(false),[discovering,setDiscovering]=useState(false),[message,setMessage]=useState(""),[config,setConfig]=useState<{valid?:boolean;missing?:string[]}>({}),[tab,setTab]=useState<"jobs"|"history">("jobs"),[selected,setSelected]=useState<string[]>([]);
 const refresh=async()=>{try{const [a,c]=await Promise.all([fetch(`${API}/api/applications`).then(r=>r.json()),fetch(`${API}/api/config/check`).then(r=>r.json())]);setApplications(a);setConfig(c)}catch{setMessage("Start the Auto Apply engine on port 8000 to connect.")}};
 useEffect(()=>{refresh()},[]);
 const counts=useMemo(()=>({applied:applications.filter(a=>a.status==="applied").length,review:applications.filter(a=>a.status==="needs_human").length,preview:applications.filter(a=>a.status==="preview").length}),[applications]);
 const discoverFreshershunt=async()=>{setDiscovering(true);setMessage("");try{const r=await fetch(`${API}/api/jobs/discover`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({freshershunt:[FRESHERSHUNT],freshershunt_max_pages:531,minimum_score:minimumScore,max_results:500})});const d=await r.json();if(!r.ok)throw Error(d.detail||"Discovery failed");setJobs(d.jobs||[]);setSelected([]);setMessage(`Imported ${d.count||0} FreshersHunt job sources. Select the jobs you want to process.`)}catch(e){setMessage(e instanceof Error?e.message:"Discovery failed")}finally{setDiscovering(false)}};
 const run=async(runUrls:string[])=>{if(!runUrls.length){setMessage("Select a job or paste a career-page URL first.");return}setLoading(true);setMessage("");try{const r=await fetch(`${API}/api/jobs/run`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({urls:runUrls,auto_submit:!dryRun})});const d=await r.json();if(!r.ok)throw Error(d.detail||"Application run failed");const applied=(d.results||[]).filter((x:Application)=>x.status==="applied").length,review=(d.results||[]).filter((x:Application)=>x.status==="needs_human").length;setMessage(dryRun?`Preview ready for ${d.results?.length||0} jobs.`:`${applied} submitted · ${review} need your review.`);setSelected([]);await refresh();setTab("history")}catch(e){setMessage(e instanceof Error?e.message:"Application run failed")}finally{setLoading(false)}};
 const toggle=(url:string)=>setSelected(s=>s.includes(url)?s.filter(x=>x!==url):[...s,url]);
 return <div className="page auto-apply-page"><section className="robo-hero"><div><div className="eyebrow">ROBOAPPLY</div><h1>Apply to jobs without the busywork.</h1><p>Import FreshersHunt openings, match them to your profile, then process compatible official application pages.</p></div><div className={`engine-pill ${config.valid?"ready":"warning"}`}>{config.valid?"● Ready to apply":"● Complete profile"}</div></section>
 <section className="robo-stats"><div><span>Applications</span><strong>{applications.length}</strong></div><div><span>Submitted</span><strong>{counts.applied}</strong></div><div><span>Needs review</span><strong>{counts.review}</strong></div><div><span>Previewed</span><strong>{counts.preview}</strong></div></section>
 <div className="robo-tabs"><button className={tab==="jobs"?"active":""} onClick={()=>setTab("jobs")}>Find jobs</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Application tracker</button></div>
 {tab==="jobs"?<><section className="discover-card"><div className="section-heading"><div><h2>FreshersHunt job queue</h2><p>Pull the public job/article list from FreshersHunt and surface the application sources. This does not submit anything on FreshersHunt itself.</p></div><span className="match-chip">AI match</span></div><label>Minimum match <b>{minimumScore}%</b><input type="range" min="0" max="100" value={minimumScore} onChange={e=>setMinimumScore(+e.target.value)}/></label><button className="primary-btn" onClick={discoverFreshershunt} disabled={discovering||!config.valid}>{discovering?"Importing FreshersHunt…":"Import all FreshersHunt jobs →"}</button>{!config.valid&&<small className="warning-text">Add {config.missing?.join(", ")||"your profile"} before running applications.</small>}</section>
 <section className="paste-card"><div><strong>Have an official job URL already?</strong><span>Paste compatible career-page URLs below.</span></div><textarea value={urls} onChange={e=>setUrls(e.target.value)} placeholder="Paste Greenhouse / Lever / compatible ATS URLs…"/><button className="secondary-btn" disabled={loading||!config.valid} onClick={()=>run(urls.split(/\n|,/).map(x=>x.trim()).filter(Boolean))}>{loading?"Running…":dryRun?"Preview applications":"Apply now"}</button></section>
 {jobs.length>0&&<section className="jobs-section"><div className="section-heading"><div><h2>FreshersHunt queue</h2><p>{selected.length?`${selected.length} selected`: `${jobs.length} imported · process in batches of ${5}`}</p></div><button className="primary-btn compact" disabled={!selected.length||loading||!config.valid} onClick={()=>run(selected.slice(0,5))}>{dryRun?"Preview selected":"Apply selected"} →</button></div><div className="job-grid">{jobs.map(j=><article className={`job-card ${selected.includes(j.url)?"selected":""}`} key={j.url} onClick={()=>toggle(j.url)}><div className="job-top"><span className="source-badge">{j.source||"FreshersHunt"}</span><span className="score">{Math.round(j.score||0)}% match</span></div><h3>{j.title}</h3><p className="company">{j.company||"Company in source page"}</p><p className="location">⌖ {j.location||"India"}</p><div className="job-bottom"><span>{selected.includes(j.url)?"✓ Selected":"Select role"}</span><a href={j.url} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Open source ↗</a></div></article>)}</div></section>}</>:<section className="tracker-card"><div className="section-heading"><div><h2>Application tracker</h2><p>Every run is deduplicated and logged locally.</p></div><button className="secondary-btn" onClick={refresh}>Refresh</button></div>{applications.length===0?<div className="empty-state"><strong>No applications yet</strong><span>Start with FreshersHunt discovery or paste a compatible career-page URL.</span></div>:<div className="application-list">{applications.map(a=><div className="application-row" key={`${a.id}-${a.url}`}><div><h3>{a.title||"Job application"}</h3><span>{a.company||a.adapter||"Career page"}</span><small>{a.url}</small></div><div className="application-status"><b className={`status-badge ${a.status}`}>{a.status.replace("_"," ")}</b><small>{a.reason||""}</small></div></div>)}</div>}</section>}
 <footer className="robo-footer"><label><input type="checkbox" checked={dryRun} onChange={e=>setDryRun(e.target.checked)}/> <b>Review before submitting</b></label><span>CAPTCHA, MFA and unknown required questions always stop for human review.</span></footer>{message&&<div className="run-message">{message}</div>}</div>;
}
